import { Link } from 'react-router-dom';
import { ShoppingBag } from 'lucide-react';
import { useAsync } from '../../hooks/useAsync';
import { api } from '../../services/api';
import { demoSubcategories } from '../../services/demoData';

export function CategoryGrid() {
  const categories = useAsync(() => api.getCategories(), []);
  return <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3"><Link to="/shop" className="group relative flex min-h-56 flex-col justify-end overflow-hidden rounded-2xl bg-gradient-to-br from-emerald-600 to-emerald-800 p-5"><div className="absolute -right-6 -top-6 h-28 w-28 rounded-full bg-white/10 transition duration-500 group-hover:scale-125" /><div className="absolute -bottom-8 -left-4 h-24 w-24 rounded-full bg-white/10" /><ShoppingBag size={22} className="mb-8 text-white/90" /><h3 className="relative text-base font-bold text-white">All Products</h3><p className="relative mt-1 text-xs text-emerald-100">Everything in one place</p></Link>{(categories.data ?? []).map((category) => <div key={category.slug} className="overflow-hidden rounded-2xl border border-slate-100 bg-white shadow-sm"><Link to={`/category/${category.slug}`} className="group relative block h-36 overflow-hidden"><img src={category.image} alt={category.name} loading="lazy" className="h-full w-full object-cover transition duration-700 group-hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-slate-950/80 via-slate-950/10 to-transparent" /><div className="absolute inset-x-0 bottom-0 p-4"><h3 className="text-base font-bold text-white">{category.name}</h3><p className="mt-0.5 text-xs text-white/70">Browse category</p></div></Link><div className="p-4"><p className="text-[11px] font-bold uppercase tracking-wide text-slate-400">Subcategories</p><div className="mt-2 flex flex-wrap gap-1.5">{(demoSubcategories[category.slug] ?? []).map((subcategory) => <Link key={subcategory.slug} to={`/category/${category.slug}?subcategory=${subcategory.slug}`} className="rounded-full bg-slate-50 px-2.5 py-1 text-xs font-medium text-slate-600 transition hover:bg-emerald-50 hover:text-emerald-700">{subcategory.name}</Link>)}</div></div></div>)}</div>;
}
