/** @param {import('knex').Knex} knex */
exports.up = async (knex) => {
  await knex.schema.createTable('carts', (t) => { t.uuid('id').primary().defaultTo(knex.raw('gen_random_uuid()')); t.uuid('user_id').notNullable().unique().references('id').inTable('users').onDelete('CASCADE'); t.timestamp('created_at').notNullable().defaultTo(knex.fn.now()); t.timestamp('updated_at').notNullable().defaultTo(knex.fn.now()); });
  await knex.schema.createTable('cart_items', (t) => { t.uuid('id').primary().defaultTo(knex.raw('gen_random_uuid()')); t.uuid('cart_id').notNullable().references('id').inTable('carts').onDelete('CASCADE'); t.uuid('product_id').notNullable().references('id').inTable('products').onDelete('CASCADE'); t.uuid('variant_id').references('id').inTable('product_variants').onDelete('SET NULL'); t.uuid('vendor_profile_id').notNullable().references('id').inTable('vendor_profiles').onDelete('CASCADE'); t.integer('quantity').notNullable(); t.integer('unit_price').notNullable(); t.string('currency').notNullable().defaultTo('RWF'); t.jsonb('selected_options').notNullable().defaultTo('{}'); t.timestamp('created_at').notNullable().defaultTo(knex.fn.now()); t.timestamp('updated_at').notNullable().defaultTo(knex.fn.now()); t.unique(['cart_id', 'product_id', 'variant_id']); });
  await knex.schema.createTable('orders', (t) => { t.uuid('id').primary().defaultTo(knex.raw('gen_random_uuid()')); t.string('order_number').notNullable().unique(); t.uuid('user_id').notNullable().references('id').inTable('users').onDelete('RESTRICT'); t.string('customer_name').notNullable(); t.string('phone').notNullable(); t.string('email').notNullable(); t.text('delivery_address').notNullable(); t.string('fulfillment_method').notNullable(); t.string('payment_method').notNullable(); t.integer('subtotal').notNullable(); t.integer('delivery_fee').notNullable().defaultTo(0); t.integer('total').notNullable(); t.string('currency').notNullable().defaultTo('RWF'); t.string('status').notNullable().defaultTo('PENDING_PAYMENT'); t.timestamp('created_at').notNullable().defaultTo(knex.fn.now()); t.timestamp('updated_at').notNullable().defaultTo(knex.fn.now()); });
  await knex.schema.createTable('vendor_orders', (t) => { t.uuid('id').primary().defaultTo(knex.raw('gen_random_uuid()')); t.uuid('order_id').notNullable().references('id').inTable('orders').onDelete('CASCADE'); t.uuid('vendor_profile_id').notNullable().references('id').inTable('vendor_profiles').onDelete('RESTRICT'); t.integer('subtotal').notNullable(); t.string('status').notNullable().defaultTo('PENDING'); t.timestamp('created_at').notNullable().defaultTo(knex.fn.now()); t.timestamp('updated_at').notNullable().defaultTo(knex.fn.now()); t.unique(['order_id', 'vendor_profile_id']); });
  await knex.schema.createTable('order_items', (t) => { t.uuid('id').primary().defaultTo(knex.raw('gen_random_uuid()')); t.uuid('vendor_order_id').notNullable().references('id').inTable('vendor_orders').onDelete('CASCADE'); t.uuid('product_id').notNullable().references('id').inTable('products').onDelete('RESTRICT'); t.uuid('variant_id').references('id').inTable('product_variants').onDelete('SET NULL'); t.uuid('inventory_item_id').references('id').inTable('inventory_items').onDelete('SET NULL'); t.string('product_name').notNullable(); t.string('variant_label'); t.integer('quantity').notNullable(); t.integer('unit_price').notNullable(); t.integer('subtotal').notNullable(); t.string('currency').notNullable().defaultTo('RWF'); t.jsonb('selected_options').notNullable().defaultTo('{}'); });
};
exports.down = async (knex) => { await knex.schema.dropTableIfExists('order_items'); await knex.schema.dropTableIfExists('vendor_orders'); await knex.schema.dropTableIfExists('orders'); await knex.schema.dropTableIfExists('cart_items'); await knex.schema.dropTableIfExists('carts'); };
