import { useEffect, useState, type FormEvent } from 'react';
import { Link } from 'react-router-dom';
import { Boxes } from 'lucide-react';
import { useAuth } from '../context/AuthContext';
import { packagesApi, type PackageRecord } from '../services/packages';

export function AdminPackagesPage() {
  const { user } = useAuth(); const [packages, setPackages] = useState<PackageRecord[]>([]); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [name, setName] = useState(''); const [price, setPrice] = useState(''); const [limit, setLimit] = useState(''); const [days, setDays] = useState('30');
  const load = () => packagesApi.list().then(setPackages).catch((err) => setError(err instanceof Error ? err.message : 'Unable to load packages'));
  useEffect(() => { if (user?.role === 'ADMIN') void load(); }, [user?.role]);
  const create = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(''); try { const created = await packagesApi.create({ name, description: null, price: Number(price), currency: 'RWF', productLimit: Number(limit), durationDays: Number(days), isActive: true }); setPackages((current) => [...current, created]); setName(''); setPrice(''); setLimit(''); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to create package'); } finally { setBusy(false); } };
  const toggle = async (pkg: PackageRecord) => { try { const updated = await packagesApi.update(pkg.id, { isActive: !pkg.isActive }); setPackages((current) => current.map((item) => item.id === updated.id ? updated : item)); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to update package'); } };
  if (!user || user.role !== 'ADMIN') return <div className="mx-auto max-w-xl px-4 py-16 text-center"><h1 className="text-xl font-bold">Admin access required</h1><Link to="/login" className="mt-4 inline-block font-semibold text-emerald-700">Sign in</Link></div>;
  return <div className="mx-auto max-w-5xl px-4 py-10 sm:px-6"><div className="flex items-center gap-3"><span className="flex h-12 w-12 items-center justify-center rounded-xl bg-slate-900 text-white"><Boxes size={22} /></span><div><h1 className="text-xl font-extrabold text-slate-900">Package management</h1><p className="text-sm text-slate-500">Package prices and entitlements are stored in the database.</p></div></div>{error && <p className="mt-5 rounded-lg bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}<form onSubmit={create} className="mt-6 grid gap-3 rounded-2xl border border-slate-100 bg-white p-6 shadow-sm sm:grid-cols-5"><input required minLength={2} value={name} onChange={(e) => setName(e.target.value)} placeholder="Package name" className="rounded-lg border border-slate-200 px-3 py-2 text-sm" /><input required type="number" min="0" value={price} onChange={(e) => setPrice(e.target.value)} placeholder="Price RWF" className="rounded-lg border border-slate-200 px-3 py-2 text-sm" /><input required type="number" min="1" value={limit} onChange={(e) => setLimit(e.target.value)} placeholder="Product limit" className="rounded-lg border border-slate-200 px-3 py-2 text-sm" /><input required type="number" min="1" value={days} onChange={(e) => setDays(e.target.value)} placeholder="Duration days" className="rounded-lg border border-slate-200 px-3 py-2 text-sm" /><button disabled={busy} className="rounded-lg bg-emerald-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-60">{busy ? 'Adding…' : 'Add package'}</button></form><div className="mt-6 overflow-x-auto rounded-2xl border border-slate-100 bg-white shadow-sm"><table className="min-w-full text-left text-sm"><thead className="border-b border-slate-100 bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-4 py-3">Package</th><th className="px-4 py-3">Price</th><th className="px-4 py-3">Published products</th><th className="px-4 py-3">Duration</th><th className="px-4 py-3">State</th><th className="px-4 py-3">Action</th></tr></thead><tbody className="divide-y divide-slate-100">{packages.map((pkg) => <tr key={pkg.id}><td className="px-4 py-4 font-semibold">{pkg.name}</td><td className="px-4 py-4">{pkg.price.toLocaleString()} {pkg.currency}</td><td className="px-4 py-4">{pkg.productLimit}</td><td className="px-4 py-4">{pkg.durationDays} days</td><td className="px-4 py-4">{pkg.isActive ? 'Active' : 'Inactive'}</td><td className="px-4 py-4"><button onClick={() => void toggle(pkg)} className="rounded-md bg-slate-800 px-3 py-2 text-xs font-semibold text-white">{pkg.isActive ? 'Deactivate' : 'Activate'}</button></td></tr>)}</tbody></table></div></div>;
}
