import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { ShieldCheck } from 'lucide-react';
import { useAuth } from '../context/AuthContext';
import { paymentsApi, type VendorPayment } from '../services/payments';

export function AdminPaymentsPage() {
  const { user } = useAuth(); const [payments, setPayments] = useState<VendorPayment[]>([]); const [error, setError] = useState(''); const [busyId, setBusyId] = useState('');
  const load = () => paymentsApi.adminList().then(setPayments).catch((err) => setError(err instanceof Error ? err.message : 'Unable to load payment records'));
  useEffect(() => { if (user?.role !== 'ADMIN') return; void load(); const timer = window.setInterval(() => void load(), 30000); return () => window.clearInterval(timer); }, [user?.role]);
  const review = async (payment: VendorPayment, decision: 'VERIFIED' | 'REJECTED') => { const note = window.prompt(decision === 'VERIFIED' ? 'Optional approval note' : 'Reason for rejection') ?? ''; setBusyId(payment.id); try { const updated = await paymentsApi.review(payment.id, decision, note); setPayments((current) => current.map((item) => item.id === updated.id ? updated : item)); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to review payment'); } finally { setBusyId(''); } };
  if (!user || user.role !== 'ADMIN') return <div className="mx-auto max-w-xl px-4 py-16 text-center"><h1 className="text-xl font-bold">Admin access required</h1><Link to="/login" className="mt-4 inline-block font-semibold text-emerald-700">Sign in</Link></div>;
  return <div className="mx-auto max-w-6xl px-4 py-10 sm:px-6"><div className="flex items-center gap-3"><span className="flex h-12 w-12 items-center justify-center rounded-xl bg-slate-900 text-white"><ShieldCheck size={22} /></span><div><h1 className="text-xl font-extrabold text-slate-900">Vendor payment review</h1><p className="text-sm text-slate-500">Review submitted payment and deal records. Verification does not activate vendors.</p></div></div>{error && <p className="mt-5 rounded-lg bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}<div className="mt-6 overflow-x-auto rounded-2xl border border-slate-100 bg-white shadow-sm"><table className="min-w-full text-left text-sm"><thead className="border-b border-slate-100 bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-4 py-3">Vendor</th><th className="px-4 py-3">Package</th><th className="px-4 py-3">Amount</th><th className="px-4 py-3">Reference</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Actions</th></tr></thead><tbody className="divide-y divide-slate-100">{payments.map((payment) => <tr key={payment.id}><td className="px-4 py-4"><div className="font-semibold text-slate-800">{payment.vendorName}</div><div className="text-xs text-slate-500">{payment.vendorEmail}<br />{payment.businessName}</div></td><td className="px-4 py-4">{payment.packageName}</td><td className="px-4 py-4">{payment.amount.toLocaleString()} {payment.currency}</td><td className="px-4 py-4">{payment.reference || '—'}</td><td className="px-4 py-4 font-semibold">{payment.status}</td><td className="px-4 py-4">{payment.status === 'PENDING_REVIEW' ? <div className="flex gap-2"><button disabled={busyId === payment.id} onClick={() => void review(payment, 'VERIFIED')} className="rounded-md bg-emerald-600 px-3 py-2 text-xs font-semibold text-white disabled:opacity-50">Verify</button><button disabled={busyId === payment.id} onClick={() => void review(payment, 'REJECTED')} className="rounded-md bg-rose-600 px-3 py-2 text-xs font-semibold text-white disabled:opacity-50">Reject</button></div> : <span className="text-xs text-slate-500">Reviewed</span>}</td></tr>)}</tbody></table>{payments.length === 0 && <p className="p-8 text-center text-sm text-slate-500">No payment records found.</p>}</div></div>;
}
