import { useEffect, useState, type FormEvent } from 'react';
import { Link } from 'react-router-dom';
import { Tags } from 'lucide-react';
import { useAuth } from '../context/AuthContext';
import { productsApi, type Category } from '../services/products';

const API_URL = (import.meta.env.VITE_API_URL ?? '').replace(/\/$/, '');
async function createCategory(name: string) { const response = await fetch(`${API_URL}/api/categories/admin`, { method: 'POST', credentials: 'include', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name }) }); if (!response.ok) throw new Error('Unable to create category'); return response.json() as Promise<Category>; }
export function AdminCategoriesPage() { const { user } = useAuth(); const [categories, setCategories] = useState<Category[]>([]); const [name, setName] = useState(''); const [error, setError] = useState(''); useEffect(() => { if (user?.role === 'ADMIN') void productsApi.categories().then(setCategories).catch((err) => setError(err instanceof Error ? err.message : 'Unable to load categories')); }, [user?.role]); const submit = async (event: FormEvent) => { event.preventDefault(); try { const created = await createCategory(name); setCategories((current) => [...current, created]); setName(''); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to create category'); } }; if (!user || user.role !== 'ADMIN') return <div className="mx-auto max-w-xl px-4 py-16 text-center"><h1 className="text-xl font-bold">Admin access required</h1><Link to="/login" className="mt-4 inline-block font-semibold text-emerald-700">Sign in</Link></div>; return <div className="mx-auto max-w-4xl px-4 py-10 sm:px-6"><div className="flex items-center gap-3"><span className="flex h-12 w-12 items-center justify-center rounded-xl bg-slate-900 text-white"><Tags size={22} /></span><div><h1 className="text-xl font-extrabold">Categories</h1><p className="text-sm text-slate-500">Manage the taxonomy vendors use for products.</p></div></div>{error && <p className="mt-5 text-sm text-rose-600">{error}</p>}<form onSubmit={submit} className="mt-6 flex gap-3 rounded-2xl bg-white p-6 shadow-sm"><input required minLength={2} value={name} onChange={(e) => setName(e.target.value)} placeholder="Category name" className="flex-1 rounded-lg border border-slate-200 px-3 py-2 text-sm" /><button className="rounded-lg bg-emerald-600 px-4 py-2 text-sm font-semibold text-white">Add category</button></form><div className="mt-6 space-y-3">{categories.map((category) => <div key={category.id} className="rounded-xl bg-white p-5 shadow-sm"><div className="font-bold">{category.name}</div><div className="mt-2 text-xs text-slate-500">{category.subcategories.length} subcategories</div></div>)}</div></div>; }
