import { useEffect, useMemo, useState } from 'react';
import { BarChart3, CheckCircle2, ClipboardCheck, Eye, ShieldAlert, XCircle } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import { getModerationListings, getPlatformAnalytics, moderateListing, type ModerationListing, type PlatformAnalytics, type ReviewStatus } from '../services/adminModeration';
import { formatPrice } from '../lib/utils';

const statusStyles: Record<ReviewStatus, string> = { PENDING_REVIEW: 'bg-amber-50 text-amber-700', APPROVED: 'bg-emerald-50 text-emerald-700', REJECTED: 'bg-rose-50 text-rose-700' };
const label = (value: string) => value.replaceAll('_', ' ').toLowerCase().replace(/(^| )\w/g, (letter) => letter.toUpperCase());
function Metric({ title, value, detail, icon: Icon }: { title: string; value: string; detail: string; icon: typeof BarChart3 }) { return <div className="rounded-2xl border border-slate-100 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><p className="text-xs font-bold uppercase tracking-wide text-slate-400">{title}</p><Icon size={17} className="text-slate-700" /></div><p className="mt-3 text-2xl font-extrabold text-slate-900">{value}</p><p className="mt-1 text-xs text-slate-500">{detail}</p></div>; }

export function AdminModerationPage() {
  const { user } = useAuth(); const [listings, setListings] = useState<ModerationListing[]>([]); const [analytics, setAnalytics] = useState<PlatformAnalytics | null>(null); const [filter, setFilter] = useState<ReviewStatus | 'ALL'>('ALL'); const [busy, setBusy] = useState(''); const [error, setError] = useState('');
  const load = async () => { try { const [nextListings, nextAnalytics] = await Promise.all([getModerationListings(), getPlatformAnalytics()]); setListings(nextListings); setAnalytics(nextAnalytics); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to load moderation data'); } };
  useEffect(() => { if (user?.role === 'ADMIN') void load(); }, [user?.role]);
  const visible = useMemo(() => filter === 'ALL' ? listings : listings.filter((listing) => listing.reviewStatus === filter), [filter, listings]);
  const act = async (listing: ModerationListing, status: Exclude<ReviewStatus, 'PENDING_REVIEW'>) => { const note = window.prompt(`${status === 'APPROVED' ? 'Approval' : 'Rejection'} note (optional):`, listing.moderationNote ?? '') ?? ''; setBusy(listing.id); const updated = await moderateListing(listing.id, status, note); setListings(updated); setAnalytics(await getPlatformAnalytics()); setBusy(''); };
  if (!user || user.role !== 'ADMIN') return <div className="mx-auto max-w-xl px-4 py-16 text-center"><h1 className="text-xl font-bold">Admin access required</h1><p className="mt-2 text-sm text-slate-500">Demo admin: admin@market.demo / admin123</p><Link to="/login" className="mt-4 inline-block font-semibold text-emerald-700">Sign in</Link></div>;
  return <div className="mx-auto max-w-7xl px-4 py-8 sm:px-6"><div className="flex flex-wrap items-center justify-between gap-4"><div className="flex items-center gap-3"><span className="flex h-12 w-12 items-center justify-center rounded-xl bg-slate-900 text-white"><ClipboardCheck size={22} /></span><div><h1 className="text-xl font-extrabold text-slate-900">Moderation center</h1><p className="text-sm text-slate-500">Review seller listings and monitor platform health.</p></div></div><Link to="/admin/operations" className="rounded-lg border border-slate-200 px-4 py-2.5 text-sm font-semibold text-slate-700">Operations overview</Link></div>{error && <p className="mt-5 rounded-lg bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}{analytics && <div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-5"><Metric title="Pending review" value={String(analytics.pendingListings)} detail="Listings needing action" icon={ShieldAlert} /><Metric title="Approved listings" value={String(analytics.approvedListings)} detail={`${analytics.approvalRate}% approval rate`} icon={CheckCircle2} /><Metric title="Platform revenue" value={formatPrice(analytics.platformRevenue)} detail={`${analytics.totalOrders} demo orders`} icon={BarChart3} /><Metric title="Taxonomy" value={`${analytics.totalCategories}/${analytics.totalSubcategories}`} detail="Categories / subcategories" icon={ClipboardCheck} /><Metric title="Active sellers" value={String(analytics.activeSellers)} detail={`${analytics.customerAccounts} customer accounts`} icon={Eye} /></div>}
    <section className="mt-7 rounded-2xl border border-slate-100 bg-white shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 px-6 py-5"><div><h2 className="font-bold text-slate-900">Seller listing review</h2><p className="mt-1 text-xs text-slate-500">Approve safe listings or reject listings that need changes.</p></div><div className="flex flex-wrap gap-2">{(['ALL', 'PENDING_REVIEW', 'APPROVED', 'REJECTED'] as const).map((item) => <button key={item} type="button" onClick={() => setFilter(item)} className={`rounded-full px-3 py-1.5 text-xs font-bold ${filter === item ? 'bg-slate-900 text-white' : 'bg-slate-100 text-slate-600'}`}>{item === 'ALL' ? 'All' : label(item)}</button>)}</div></div><div className="divide-y divide-slate-100">{visible.map((listing) => <article key={listing.id} className="flex flex-col gap-4 px-6 py-5 lg:flex-row lg:items-center lg:justify-between"><div className="flex min-w-0 items-center gap-4"><div className="h-16 w-16 shrink-0 overflow-hidden rounded-xl bg-slate-50"><img src={listing.images[0]?.url} alt="" className="h-full w-full object-cover" /></div><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h3 className="font-bold text-slate-900">{listing.name}</h3><span className={`rounded-full px-2.5 py-1 text-[11px] font-bold ${statusStyles[listing.reviewStatus]}`}>{label(listing.reviewStatus)}</span></div><p className="mt-1 text-sm text-slate-500">{listing.categoryName ?? 'Uncategorized'}{listing.subcategoryName ? ` · ${listing.subcategoryName}` : ''} · {listing.sellerName}</p><p className="mt-1 text-xs text-slate-400">{formatPrice(listing.price)} · Submitted {new Date(listing.submittedAt).toLocaleDateString('en-GB')}</p>{listing.moderationNote && <p className="mt-2 text-xs text-slate-500">Note: {listing.moderationNote}</p>}</div></div><div className="flex shrink-0 gap-2">{listing.reviewStatus !== 'APPROVED' && <button type="button" disabled={busy === listing.id} onClick={() => void act(listing, 'APPROVED')} className="flex items-center gap-1.5 rounded-lg bg-emerald-600 px-3 py-2 text-xs font-bold text-white disabled:opacity-50"><CheckCircle2 size={14} /> Approve</button>}{listing.reviewStatus !== 'REJECTED' && <button type="button" disabled={busy === listing.id} onClick={() => void act(listing, 'REJECTED')} className="flex items-center gap-1.5 rounded-lg bg-rose-600 px-3 py-2 text-xs font-bold text-white disabled:opacity-50"><XCircle size={14} /> Reject</button>}</div></article>)}{visible.length === 0 && <p className="px-6 py-12 text-center text-sm text-slate-500">No listings in this review queue.</p>}</div></section></div>;
}
