import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { Shield } from 'lucide-react';
import { useAuth } from '../context/AuthContext';
import { vendorsApi, type ManagedVendor } from '../services/vendors';

const actionsFor = (status: string) => status === 'PENDING_APPROVAL' ? ['ACTIVATE', 'DEACTIVATE'] : status === 'ACTIVE' || status === 'EXPIRING_SOON' || status === 'EXPIRED' ? ['SUSPEND', 'DEACTIVATE'] : status === 'SUSPENDED' || status === 'DEACTIVATED' ? ['REACTIVATE'] : ['DEACTIVATE'];
const formatDate = (value: string | null) => value ? new Date(value).toLocaleDateString() : 'Not activated';

export function AdminVendorsPage() {
  const { user } = useAuth(); const [vendors, setVendors] = useState<ManagedVendor[]>([]); const [error, setError] = useState(''); const [busyId, setBusyId] = useState('');
  const load = () => vendorsApi.list().then(setVendors).catch((err) => setError(err instanceof Error ? err.message : 'Unable to load vendors'));
  useEffect(() => { if (user?.role !== 'ADMIN') return; void load(); const timer = window.setInterval(() => void load(), 30000); return () => window.clearInterval(timer); }, [user?.role]);
  const act = async (vendor: ManagedVendor, action: 'ACTIVATE' | 'SUSPEND' | 'DEACTIVATE' | 'REACTIVATE') => { const note = window.prompt(`${action} ${vendor.businessName}. Optional note:`) ?? ''; setBusyId(vendor.id); try { const updated = await vendorsApi.action(vendor.id, action, note); setVendors((current) => current.map((item) => item.id === updated.id ? updated : item)); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to update vendor'); } finally { setBusyId(''); } };
  if (!user || user.role !== 'ADMIN') return <div className="mx-auto max-w-xl px-4 py-16 text-center"><h1 className="text-xl font-bold">Admin access required</h1><Link to="/login" className="mt-4 inline-block font-semibold text-emerald-700">Sign in</Link></div>;
  return <div className="mx-auto max-w-7xl px-4 py-10 sm:px-6"><div className="flex items-center gap-3"><span className="flex h-12 w-12 items-center justify-center rounded-xl bg-slate-900 text-white"><Shield size={22} /></span><div><h1 className="text-xl font-extrabold text-slate-900">Vendor management</h1><p className="text-sm text-slate-500">Manage vendor account status. Every action is server-validated and audited.</p></div></div>{error && <p className="mt-5 rounded-lg bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}<div className="mt-6 overflow-x-auto rounded-2xl border border-slate-100 bg-white shadow-sm"><table className="min-w-full text-left text-sm"><thead className="border-b border-slate-100 bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-4 py-3">Vendor</th><th className="px-4 py-3">Contact</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Subscription</th><th className="px-4 py-3">Latest payment</th><th className="px-4 py-3">Actions</th></tr></thead><tbody className="divide-y divide-slate-100">{vendors.map((vendor) => <tr key={vendor.id}><td className="px-4 py-4"><div className="font-semibold text-slate-800">{vendor.businessName}</div><div className="text-xs text-slate-500">{vendor.name}</div></td><td className="px-4 py-4 text-xs text-slate-600">{vendor.email}<br />{vendor.phone}<br />{vendor.location}</td><td className="px-4 py-4"><span className="font-semibold">{vendor.status}</span><div className="text-xs text-slate-500">Email {vendor.emailVerified ? 'verified' : 'unverified'}</div></td><td className="px-4 py-4 text-xs"><div>Activated: {formatDate(vendor.subscriptionStartDate)}</div><div className="mt-1 font-semibold text-slate-700">Expires: {formatDate(vendor.subscriptionEndDate)}</div></td><td className="px-4 py-4 text-xs">{vendor.latestPayment ? `${vendor.latestPayment.amount.toLocaleString()} ${vendor.latestPayment.currency} · ${vendor.latestPayment.status}` : 'None'}</td><td className="px-4 py-4"><div className="flex flex-wrap gap-2">{actionsFor(vendor.status).map((action) => <button key={action} disabled={busyId === vendor.id} onClick={() => void act(vendor, action as 'ACTIVATE' | 'SUSPEND' | 'DEACTIVATE' | 'REACTIVATE')} className="rounded-md bg-slate-800 px-3 py-2 text-xs font-semibold text-white disabled:opacity-50">{action}</button>)}</div></td></tr>)}</tbody></table>{vendors.length === 0 && <p className="p-8 text-center text-sm text-slate-500">No vendors found.</p>}</div></div>;
}
