import { useEffect, useState, type FormEvent } from 'react';
import { Link } from 'react-router-dom';
import { CreditCard } from 'lucide-react';
import { useAuth } from '../context/AuthContext';
import { useToast } from '../context/ToastContext';
import { paymentsApi, type PaymentPackage, type VendorPayment } from '../services/payments';

export function VendorPaymentPage() {
  const { user } = useAuth(); const { toast } = useToast(); const [packages, setPackages] = useState<PaymentPackage[]>([]); const [payments, setPayments] = useState<VendorPayment[]>([]); const [packageId, setPackageId] = useState(''); const [method, setMethod] = useState('Mobile Money'); const [reference, setReference] = useState(''); const [notes, setNotes] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  useEffect(() => { Promise.all([paymentsApi.packages(), paymentsApi.mine()]).then(([nextPackages, nextPayments]) => { setPackages(nextPackages); setPayments(nextPayments); setPackageId(nextPackages[0]?.id ?? ''); }).catch((err) => setError(err instanceof Error ? err.message : 'Unable to load payment details')); }, []);
  const submit = async (e: FormEvent) => { e.preventDefault(); if (busy) return; if (!packageId || method.trim().length < 2 || reference.trim().length < 3) { setError('Select a package and provide a payment method and transaction reference.'); return; } setBusy(true); setError(''); try { await paymentsApi.submit({ packageId, paymentMethod: method.trim(), reference: reference.trim(), notes: notes.trim() }); setPayments(await paymentsApi.mine()); setReference(''); setNotes(''); toast('Payment recorded and sent for admin review.'); } catch (err) { const message = err instanceof Error ? err.message : 'Unable to submit payment'; setError(message.toLowerCase().includes('reference') ? 'That transaction reference has already been submitted. Check your payment history or use the correct reference.' : message); } finally { setBusy(false); } };
  if (!user || user.role !== 'VENDOR') return <div className="mx-auto max-w-xl px-4 py-16 text-center"><h1 className="text-xl font-bold">Vendor access required</h1><Link to="/login" className="mt-4 inline-block font-semibold text-emerald-700">Sign in</Link></div>;
  return <div className="mx-auto max-w-3xl px-4 py-10 sm:px-6"><div className="rounded-2xl border border-slate-100 bg-white p-7 shadow-sm"><span className="flex h-12 w-12 items-center justify-center rounded-xl bg-emerald-600 text-white"><CreditCard size={22} /></span><h1 className="mt-4 text-xl font-extrabold text-slate-900">Vendor payment</h1><p className="mt-1 text-sm text-slate-500">Submit your package payment or deal reference. An admin must verify it before activation.</p><form onSubmit={submit} className="mt-6 space-y-4"><label className="block"><span className="mb-1.5 block text-sm font-medium text-slate-700">Package</span><select value={packageId} onChange={(e) => setPackageId(e.target.value)} className="w-full rounded-lg border border-slate-200 px-3.5 py-2.5 text-sm">{packages.map((pkg) => <option key={pkg.id} value={pkg.id}>{pkg.name} — {pkg.price.toLocaleString()} {pkg.currency} / {pkg.durationDays} days</option>)}</select></label><label className="block"><span className="mb-1.5 block text-sm font-medium text-slate-700">Payment method</span><input value={method} onChange={(e) => setMethod(e.target.value)} className="w-full rounded-lg border border-slate-200 px-3.5 py-2.5 text-sm" /></label><label className="block"><span className="mb-1.5 block text-sm font-medium text-slate-700">Reference</span><input value={reference} onChange={(e) => setReference(e.target.value)} placeholder="Transaction or deal reference" className="w-full rounded-lg border border-slate-200 px-3.5 py-2.5 text-sm" /></label><label className="block"><span className="mb-1.5 block text-sm font-medium text-slate-700">Notes</span><textarea value={notes} onChange={(e) => setNotes(e.target.value)} rows={3} className="w-full rounded-lg border border-slate-200 px-3.5 py-2.5 text-sm" /></label>{error && <p className="text-sm text-rose-600">{error}</p>}<button disabled={busy || !packageId} className="rounded-lg bg-emerald-600 px-5 py-3 text-sm font-semibold text-white disabled:opacity-60">{busy ? 'Submitting…' : 'Record payment for review'}</button></form></div><div className="mt-6 rounded-2xl border border-slate-100 bg-white p-7 shadow-sm"><h2 className="font-bold text-slate-900">Your payment records</h2><div className="mt-4 space-y-3">{payments.length === 0 ? <p className="text-sm text-slate-500">No payment records yet.</p> : payments.map((payment) => <div key={payment.id} className="flex flex-wrap items-center justify-between gap-3 rounded-lg bg-slate-50 px-4 py-3 text-sm"><span>{payment.packageName ?? 'Package'} · {payment.amount.toLocaleString()} {payment.currency}</span><span className="font-semibold text-slate-700">{payment.status}</span></div>)}</div></div></div>;
}
