import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { CalendarClock } from 'lucide-react';
import { useAuth } from '../context/AuthContext';
import { subscriptionsApi, type Subscription, type Renewal } from '../services/subscriptions';

function formatDate(value: string) { return new Intl.DateTimeFormat(undefined, { dateStyle: 'medium' }).format(new Date(value)); }
export function VendorSubscriptionPage() {
  const { user } = useAuth(); const [subscription, setSubscription] = useState<Subscription | null>(null); const [renewals, setRenewals] = useState<Renewal[]>([]); const [seconds, setSeconds] = useState(0); const [error, setError] = useState('');
  useEffect(() => { if (user?.role === 'VENDOR') void subscriptionsApi.vendor().then((result) => { setSubscription(result.subscription); setRenewals(result.renewals); setSeconds(result.subscription?.remainingSeconds ?? 0); }).catch((err) => setError(err instanceof Error ? err.message : 'Unable to load subscription')); }, [user?.role]);
  useEffect(() => { if (seconds <= 0) return undefined; const timer = window.setInterval(() => setSeconds((value) => Math.max(0, value - 1)), 1000); return () => window.clearInterval(timer); }, [seconds]);
  if (!user || user.role !== 'VENDOR') return <div className="mx-auto max-w-xl px-4 py-16 text-center"><h1 className="text-xl font-bold">Vendor access required</h1><Link to="/login" className="mt-4 inline-block font-semibold text-emerald-700">Sign in</Link></div>;
  const countdownDays = Math.ceil(seconds / 86400); const countdownHours = Math.floor((seconds % 86400) / 3600);
  return <div className="mx-auto max-w-3xl px-4 py-10 sm:px-6"><div className="rounded-2xl border border-slate-100 bg-white p-7 shadow-sm"><span className="flex h-12 w-12 items-center justify-center rounded-xl bg-emerald-600 text-white"><CalendarClock size={22} /></span><h1 className="mt-4 text-xl font-extrabold text-slate-900">Subscription</h1>{error && <p className="mt-4 text-sm text-rose-600">{error}</p>}{!error && !subscription && <p className="mt-4 text-sm text-slate-500">No subscription yet. Admin activation starts the subscription clock.</p>}{subscription && <><div className="mt-6 grid gap-4 sm:grid-cols-2"><div className="rounded-lg bg-slate-50 p-4"><p className="text-xs uppercase tracking-wide text-slate-500">Package</p><p className="mt-1 text-lg font-bold">{subscription.packageName}</p></div><div className="rounded-lg bg-slate-50 p-4"><p className="text-xs uppercase tracking-wide text-slate-500">Status</p><p className="mt-1 text-lg font-bold text-emerald-700">{subscription.status}</p></div><div className="rounded-lg bg-slate-50 p-4"><p className="text-xs uppercase tracking-wide text-slate-500">Started</p><p className="mt-1 font-semibold">{formatDate(subscription.startDate)}</p></div><div className="rounded-lg bg-slate-50 p-4"><p className="text-xs uppercase tracking-wide text-slate-500">Expires</p><p className="mt-1 font-semibold">{formatDate(subscription.endDate)}</p></div></div><div className="mt-5 rounded-xl bg-emerald-50 p-5"><p className="text-sm text-emerald-800">Backend-calculated time remaining</p><p className="mt-1 text-2xl font-extrabold text-emerald-900">{countdownDays} days {countdownHours} hours</p><p className="mt-1 text-xs text-emerald-700">The browser timer only displays the API’s authoritative expiry timestamp.</p></div><h2 className="mt-8 font-bold text-slate-900">Renewal history</h2><div className="mt-3 space-y-2">{renewals.map((renewal) => <div key={renewal.id} className="flex flex-wrap justify-between gap-2 rounded-lg bg-slate-50 px-4 py-3 text-sm"><span>{formatDate(renewal.startDate)} → {formatDate(renewal.endDate)}</span><span className="font-semibold">{renewal.amount.toLocaleString()} {renewal.currency}</span></div>)}</div></>}</div></div>;
}
