import { useState, type FormEvent } from 'react';
import { Link, useNavigate, useSearchParams } from 'react-router-dom';
import { Store, X } from 'lucide-react';
import { useAuth } from '../context/AuthContext';
import { useToast } from '../context/ToastContext';
import { cx } from '../lib/utils';

const TERMS_VERSION = 'vendor-terms-v1';
const inputClass = (error?: string) => cx('w-full rounded-lg border px-3.5 py-2.5 text-sm transition focus:outline-none focus:ring-2', error ? 'border-rose-400 focus:border-rose-500 focus:ring-rose-500/20' : 'border-slate-200 focus:border-emerald-500 focus:ring-emerald-500/20');

function TermsModal({ onClose, onAccept, busy }: { onClose: () => void; onAccept: () => void; busy: boolean }) {
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4" role="dialog" aria-modal="true" aria-labelledby="terms-title">
    <div className="max-h-[90vh] w-full max-w-lg overflow-hidden rounded-2xl bg-white shadow-xl">
      <div className="flex items-center justify-between border-b border-slate-100 px-6 py-4"><div><h2 id="terms-title" className="font-bold text-slate-900">Vendor Terms & Conditions</h2><p className="text-xs text-slate-500">Version {TERMS_VERSION}</p></div><button type="button" onClick={onClose} aria-label="Close terms" className="rounded-lg p-2 text-slate-400 hover:bg-slate-100"><X size={18} /></button></div>
      <div className="max-h-[55vh] overflow-y-auto px-6 py-5 text-sm leading-relaxed text-slate-600"><p className="mb-4">By joining Market as a vendor, you agree to operate your shop responsibly and honestly.</p><ol className="list-decimal space-y-3 pl-5"><li>You are responsible for accurate product information, pricing, availability, images, and fulfillment.</li><li>Do not list prohibited, illegal, unsafe, counterfeit, or infringing products or content.</li><li>You are responsible for responding to customer orders and complying with applicable payment, tax, and consumer rules.</li><li>Subscription and platform fees, expiration, renewal, refund, and cancellation rules are controlled by the applicable package and platform policy.</li><li>Market may review, suspend, deactivate, or terminate shops that breach these terms or endanger customers.</li><li>You confirm that you own or have permission to use all images, descriptions, logos, and other content you upload.</li><li>Accepting these terms does not activate your vendor account. Payment review and admin activation are required before marketplace operations begin.</li></ol></div>
      <div className="flex justify-end gap-3 border-t border-slate-100 px-6 py-4"><button type="button" onClick={onClose} className="rounded-lg border border-slate-200 px-4 py-2.5 text-sm font-semibold text-slate-700">Cancel</button><button type="button" disabled={busy} onClick={onAccept} className="rounded-lg bg-emerald-600 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-60">{busy ? 'Registering…' : 'Accept & register'}</button></div>
    </div>
  </div>;
}

export function VendorRegistrationPage() {
  const [searchParams] = useSearchParams(); const redirect = searchParams.get('redirect') ?? '/'; const navigate = useNavigate();
  const { registerVendor } = useAuth(); const { toast } = useToast();
  const [name, setName] = useState(''); const [businessName, setBusinessName] = useState(''); const [email, setEmail] = useState(''); const [phone, setPhone] = useState(''); const [location, setLocation] = useState(''); const [password, setPassword] = useState(''); const [confirmPassword, setConfirmPassword] = useState('');
  const [error, setError] = useState(''); const [showTerms, setShowTerms] = useState(false); const [busy, setBusy] = useState(false);
  const submit = (e: FormEvent) => { e.preventDefault(); setError(''); if (name.trim().length < 2 || businessName.trim().length < 2 || !/^\S+@\S+\.\S+$/.test(email.trim()) || phone.trim().length < 3 || location.trim().length < 2 || password.length < 8 || password !== confirmPassword) { setError('Complete all fields, use at least 8 password characters, and make the passwords match.'); return; } setShowTerms(true); };
  const acceptAndRegister = async () => { setBusy(true); try { const result = await registerVendor({ name: name.trim(), businessName: businessName.trim(), email: email.trim(), phone: phone.trim(), location: location.trim(), password, confirmPassword, termsVersion: TERMS_VERSION }); toast(`Application received for ${result.user.name}. Your vendor account is pending payment and admin activation.`); navigate(redirect, { replace: true }); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to submit vendor registration'); setShowTerms(false); } finally { setBusy(false); } };
  const field = (label: string, value: string, setValue: (value: string) => void, type = 'text', placeholder = '') => <label className="block"><span className="mb-1.5 block text-sm font-medium text-slate-700">{label}</span><input required type={type} value={value} onChange={(e) => setValue(e.target.value)} placeholder={placeholder} className={inputClass(error)} /></label>;
  return <div className="mx-auto flex max-w-2xl flex-col px-4 py-10 sm:px-6"><div className="rounded-2xl border border-slate-100 bg-white p-7 shadow-sm"><span className="flex h-12 w-12 items-center justify-center rounded-xl bg-emerald-600 text-white"><Store size={22} /></span><h1 className="mt-4 text-xl font-extrabold text-slate-900">Become a Market vendor</h1><p className="mt-1 text-sm text-slate-500">Create your shop application. Payment review and admin activation happen after registration.</p><form onSubmit={submit} className="mt-6 space-y-4" noValidate><div className="grid gap-4 sm:grid-cols-2">{field('Full name', name, setName, 'text', 'Aline Uwase')}{field('Business / shop name', businessName, setBusinessName, 'text', 'Aline Home Store')}{field('Email', email, setEmail, 'email', 'you@example.com')}{field('Phone number', phone, setPhone, 'tel', '078 812 3456')}{field('Location', location, setLocation, 'text', 'Kigali, Rwanda')}</div><div className="grid gap-4 sm:grid-cols-2">{field('Password', password, setPassword, 'password', 'Min. 8 characters')}{field('Confirm password', confirmPassword, setConfirmPassword, 'password', 'Repeat password')}</div>{error && <p className="text-sm text-rose-600">{error}</p>}<button type="submit" className="w-full rounded-lg bg-emerald-600 py-3 text-sm font-semibold text-white hover:bg-emerald-700">Continue to Terms & Conditions</button></form><p className="mt-5 text-center text-sm text-slate-500">Already have an account? <Link to="/login" className="font-semibold text-emerald-700 hover:underline">Sign in</Link></p></div>{showTerms && <TermsModal busy={busy} onClose={() => setShowTerms(false)} onAccept={acceptAndRegister} />}</div>;
}
