import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { LayoutDashboard } from 'lucide-react';
import { useAuth } from '../context/AuthContext';
import { shopsApi, type Dashboard } from '../services/shops';

export function VendorDashboardPage() {
  const { user } = useAuth(); const [data, setData] = useState<Dashboard | null>(null); const [error, setError] = useState('');
  useEffect(() => { if (user?.role === 'VENDOR') void shopsApi.dashboard().then(setData).catch((err) => setError(err instanceof Error ? err.message : 'Unable to load dashboard')); }, [user?.role]);
  if (!user || user.role !== 'VENDOR') return <div className="mx-auto max-w-xl px-4 py-16 text-center"><h1 className="text-xl font-bold">Vendor access required</h1><Link to="/login" className="mt-4 inline-block font-semibold text-emerald-700">Sign in</Link></div>;
  return <div className="mx-auto max-w-5xl px-4 py-10 sm:px-6"><div className="flex items-center gap-3"><span className="flex h-12 w-12 items-center justify-center rounded-xl bg-emerald-600 text-white"><LayoutDashboard size={22} /></span><div><h1 className="text-xl font-extrabold text-slate-900">Welcome, {user.name.split(' ')[0]}</h1><p className="text-sm text-slate-500">Your Market vendor dashboard</p></div></div>{error && <p className="mt-5 text-sm text-rose-600">{error}</p>}{data && <><div className="mt-6 grid gap-4 sm:grid-cols-4"><div className="rounded-xl bg-white p-5 shadow-sm"><p className="text-xs text-slate-500">Shop status</p><p className="mt-1 font-bold">{data.vendorStatus}</p></div><div className="rounded-xl bg-white p-5 shadow-sm"><p className="text-xs text-slate-500">Subscription</p><p className="mt-1 font-bold">{(data.subscription as { status?: string } | null)?.status ?? 'Not started'}</p></div><div className="rounded-xl bg-white p-5 shadow-sm"><p className="text-xs text-slate-500">Published products</p><p className="mt-1 font-bold">{data.publishedProductCount}</p></div><div className="rounded-xl bg-white p-5 shadow-sm"><p className="text-xs text-slate-500">Payment records</p><p className="mt-1 font-bold">{data.paymentCount}</p></div></div><div className="mt-6 rounded-2xl bg-white p-7 shadow-sm"><h2 className="font-bold text-slate-900">{data.shop.businessName}</h2><p className="mt-1 text-sm text-slate-500">{data.shop.description || 'Add a description to tell customers about your shop.'}</p><div className="mt-5 flex flex-wrap gap-3"><Link to="/vendor/shop" className="rounded-lg bg-emerald-600 px-4 py-2.5 text-sm font-semibold text-white">Manage shop</Link><Link to="/vendor/subscription" className="rounded-lg border border-slate-200 px-4 py-2.5 text-sm font-semibold text-slate-700">View subscription</Link><Link to={`/shop/${data.shop.slug}`} className="rounded-lg border border-slate-200 px-4 py-2.5 text-sm font-semibold text-slate-700">Public shop</Link></div></div></>}</div>;
}
