import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { BarChart3, ExternalLink, LayoutDashboard, Package, ShoppingBag, Truck } from 'lucide-react';
import { useAuth } from '../context/AuthContext';
import { getSellerAnalytics, getSellerOrders, getSellerProducts, getSellerStatusLabel, updateSellerOrderStatus, type SellerAnalytics, type SellerOrder, type SellerOrderStatus } from '../services/seller';
import type { Product } from '../services/products';
import { formatPrice } from '../lib/utils';

const statusStyles: Record<SellerOrderStatus, string> = { PENDING: 'bg-amber-50 text-amber-700', PROCESSING: 'bg-blue-50 text-blue-700', READY_FOR_DELIVERY: 'bg-violet-50 text-violet-700', OUT_FOR_DELIVERY: 'bg-orange-50 text-orange-700', DELIVERED: 'bg-emerald-50 text-emerald-700', CANCELLED: 'bg-rose-50 text-rose-700' };
const money = (value: number) => formatPrice(value);

function StatCard({ label, value, detail, icon: Icon }: { label: string; value: string; detail: string; icon: typeof Package }) { return <div className="rounded-2xl border border-slate-100 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><p className="text-xs font-semibold uppercase tracking-wide text-slate-400">{label}</p><Icon size={17} className="text-emerald-600" /></div><p className="mt-3 text-2xl font-extrabold text-slate-900">{value}</p><p className="mt-1 text-xs text-slate-500">{detail}</p></div>; }

export function VendorDashboardPage() {
  const { user } = useAuth(); const [products, setProducts] = useState<Product[]>([]); const [orders, setOrders] = useState<SellerOrder[]>([]); const [analytics, setAnalytics] = useState<SellerAnalytics | null>(null); const [error, setError] = useState(''); const [busyOrder, setBusyOrder] = useState('');
  const load = async () => { try { const [nextProducts, nextOrders, nextAnalytics] = await Promise.all([getSellerProducts(), getSellerOrders(), getSellerAnalytics()]); setProducts(nextProducts); setOrders(nextOrders); setAnalytics(nextAnalytics); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to load seller dashboard'); } };
  useEffect(() => { if (user?.role === 'VENDOR') void load(); }, [user?.role]);
  const maxRevenue = useMemo(() => Math.max(...(analytics?.recentRevenue.map((item) => item.value) ?? [1]), 1), [analytics]);
  const changeStatus = async (order: SellerOrder, status: SellerOrderStatus) => { setBusyOrder(order.id); setOrders(await updateSellerOrderStatus(order.id, status)); setAnalytics(await getSellerAnalytics()); setBusyOrder(''); };
  if (!user || user.role !== 'VENDOR') return <div className="mx-auto max-w-xl px-4 py-16 text-center"><h1 className="text-xl font-bold">Seller access required</h1><Link to="/login" className="mt-4 inline-block font-semibold text-emerald-700">Sign in</Link></div>;
  return <div className="mx-auto max-w-7xl px-4 py-8 sm:px-6">
    <div className="flex flex-wrap items-center justify-between gap-4"><div className="flex items-center gap-3"><span className="flex h-12 w-12 items-center justify-center rounded-xl bg-emerald-600 text-white"><LayoutDashboard size={22} /></span><div><h1 className="text-xl font-extrabold text-slate-900">Seller dashboard</h1><p className="text-sm text-slate-500">Welcome back, {user.name.split(' ')[0]}. Manage your Market shop in one place.</p></div></div><div className="flex gap-2"><Link to="/vendor/products" className="rounded-lg bg-emerald-600 px-4 py-2.5 text-sm font-semibold text-white">Manage products</Link><Link to="/shop/demo-seller" className="flex items-center gap-2 rounded-lg border border-slate-200 px-4 py-2.5 text-sm font-semibold text-slate-700"><ExternalLink size={15} />Public shop</Link></div></div>
    {error && <p className="mt-5 rounded-lg bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}
    {analytics && <>
      <div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-5"><StatCard label="Revenue" value={money(analytics.revenue)} detail="Completed orders" icon={BarChart3} /><StatCard label="Orders" value={String(analytics.totalOrders)} detail={`${analytics.pendingOrders} need attention`} icon={ShoppingBag} /><StatCard label="Units sold" value={String(analytics.unitsSold)} detail="Across active orders" icon={Package} /><StatCard label="Avg. order" value={money(analytics.averageOrderValue)} detail="Completed order value" icon={BarChart3} /><StatCard label="Products" value={String(products.length)} detail={`${products.filter((product) => product.status === 'PUBLISHED').length} published`} icon={Package} /></div>
      <div className="mt-6 grid gap-6 lg:grid-cols-[1.4fr_1fr]"><section className="rounded-2xl border border-slate-100 bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="font-bold text-slate-900">Revenue overview</h2><p className="mt-1 text-xs text-slate-500">Demo sales activity over the last 7 days</p></div><BarChart3 size={19} className="text-emerald-600" /></div><div className="mt-6 flex h-44 items-end gap-3">{analytics.recentRevenue.map((item) => <div key={item.label} className="flex flex-1 flex-col items-center gap-2"><div className="flex h-36 w-full items-end"><div className="w-full rounded-t-lg bg-emerald-500 transition hover:bg-emerald-600" style={{ height: `${Math.max(8, (item.value / maxRevenue) * 100)}%` }} title={money(item.value)} /></div><span className="text-[11px] text-slate-400">{item.label}</span></div>)}</div></section><section className="rounded-2xl border border-slate-100 bg-white p-6 shadow-sm"><h2 className="font-bold text-slate-900">Top products</h2><div className="mt-4 divide-y divide-slate-100">{analytics.topProducts.map((product) => <div key={product.name} className="flex items-center justify-between gap-3 py-3 text-sm"><div className="min-w-0"><p className="truncate font-semibold text-slate-800">{product.name}</p><p className="text-xs text-slate-400">{product.unitsSold} units sold</p></div><span className="shrink-0 font-bold text-slate-900">{money(product.revenue)}</span></div>)}</div></section></div>
      <section className="mt-6 rounded-2xl border border-slate-100 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 px-6 py-5"><div><h2 className="font-bold text-slate-900">Order tracking</h2><p className="mt-1 text-xs text-slate-500">Update fulfillment status as orders move through your shop.</p></div><Truck size={19} className="text-emerald-600" /></div><div className="divide-y divide-slate-100">{orders.map((order) => <div key={order.id} className="flex flex-col gap-3 px-6 py-4 lg:flex-row lg:items-center lg:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><p className="font-bold text-slate-900">{order.id}</p><span className={`rounded-full px-2.5 py-1 text-[11px] font-bold ${statusStyles[order.status]}`}>{getSellerStatusLabel(order.status)}</span></div><p className="mt-1 text-sm text-slate-500">{order.customerName} · {order.customerLocation} · {new Date(order.createdAt).toLocaleDateString('en-GB')}</p><p className="mt-1 truncate text-xs text-slate-400">{order.items.map((item) => `${item.productName} ×${item.quantity}`).join(' · ')}</p></div><div className="flex items-center gap-4"><span className="font-bold text-slate-900">{money(order.total)}</span><select disabled={busyOrder === order.id} value={order.status} onChange={(event) => void changeStatus(order, event.target.value as SellerOrderStatus)} className="rounded-lg border border-slate-200 bg-white px-3 py-2 text-xs font-semibold text-slate-700"><option value="PENDING">Pending</option><option value="PROCESSING">Processing</option><option value="READY_FOR_DELIVERY">Ready for delivery</option><option value="OUT_FOR_DELIVERY">Out for delivery</option><option value="DELIVERED">Delivered</option><option value="CANCELLED">Cancelled</option></select></div></div>)}{orders.length === 0 && <p className="px-6 py-10 text-center text-sm text-slate-500">No orders yet.</p>}</div></section>
      <section className="mt-6 rounded-2xl border border-slate-100 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 px-6 py-5"><div><h2 className="font-bold text-slate-900">Posted products</h2><p className="mt-1 text-xs text-slate-500">Quick view of your local demo inventory.</p></div><Link to="/vendor/products" className="text-sm font-semibold text-emerald-700">Open product manager</Link></div><div className="grid gap-3 p-5 sm:grid-cols-2 lg:grid-cols-4">{products.slice(0, 8).map((product) => <div key={product.id} className="rounded-xl border border-slate-100 p-4"><div className="flex items-start justify-between gap-2"><p className="line-clamp-2 text-sm font-semibold text-slate-800">{product.name}</p><span className={`shrink-0 rounded-full px-2 py-1 text-[10px] font-bold ${product.status === 'PUBLISHED' ? 'bg-emerald-50 text-emerald-700' : 'bg-slate-100 text-slate-500'}`}>{product.status}</span></div><p className="mt-3 text-sm font-bold text-slate-900">{money(product.price)}</p><p className="mt-1 text-xs text-slate-400">{product.categoryName ?? 'Uncategorized'}{product.subcategoryName ? ` · ${product.subcategoryName}` : ''}</p></div>)}</div></section>
    </>}
  </div>;
}
