import { useEffect, useState, type FormEvent } from 'react';
import { Link } from 'react-router-dom';
import { Store } from 'lucide-react';
import { useAuth } from '../context/AuthContext';
import { shopsApi, type Shop } from '../services/shops';

const platforms = ['whatsapp', 'facebook', 'instagram', 'tiktok', 'x', 'youtube', 'website'];
export function VendorShopPage() {
  const { user } = useAuth(); const [shop, setShop] = useState<Shop | null>(null); const [businessName, setBusinessName] = useState(''); const [description, setDescription] = useState(''); const [phone, setPhone] = useState(''); const [location, setLocation] = useState(''); const [links, setLinks] = useState<Record<string, string>>({}); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  useEffect(() => { if (user?.role === 'VENDOR') void shopsApi.me().then((data) => { setShop(data); setBusinessName(data.businessName); setDescription(data.description ?? ''); setPhone(data.phone); setLocation(data.location); setLinks(Object.fromEntries(data.socialLinks.map((link) => [link.platform, link.url]))); }).catch((err) => setError(err instanceof Error ? err.message : 'Unable to load shop')); }, [user?.role]);
  const save = async (event: FormEvent) => { event.preventDefault(); setMessage(''); setError(''); try { const data = await shopsApi.update({ businessName, description, phone, location, socialLinks: Object.entries(links).filter(([, url]) => url.trim()).map(([platform, url]) => ({ platform, url })) }); setShop(data); setMessage('Shop profile saved.'); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to save shop'); } };
  if (!user || user.role !== 'VENDOR') return <div className="mx-auto max-w-xl px-4 py-16 text-center"><h1 className="text-xl font-bold">Vendor access required</h1><Link to="/login" className="mt-4 inline-block font-semibold text-emerald-700">Sign in</Link></div>;
  return <div className="mx-auto max-w-3xl px-4 py-10 sm:px-6"><div className="rounded-2xl border border-slate-100 bg-white p-7 shadow-sm"><span className="flex h-12 w-12 items-center justify-center rounded-xl bg-emerald-600 text-white"><Store size={22} /></span><h1 className="mt-4 text-xl font-extrabold text-slate-900">Manage shop</h1><p className="mt-1 text-sm text-slate-500">Your public shop is visible only while the account is active.</p><form onSubmit={save} className="mt-6 space-y-4"><label className="block text-sm font-medium text-slate-700">Business name<input required minLength={2} value={businessName} onChange={(e) => setBusinessName(e.target.value)} className="mt-1.5 w-full rounded-lg border border-slate-200 px-3.5 py-2.5 font-normal" /></label><label className="block text-sm font-medium text-slate-700">Description<textarea value={description} onChange={(e) => setDescription(e.target.value)} rows={4} className="mt-1.5 w-full rounded-lg border border-slate-200 px-3.5 py-2.5 font-normal" /></label><div className="grid gap-4 sm:grid-cols-2"><label className="block text-sm font-medium text-slate-700">Phone<input required value={phone} onChange={(e) => setPhone(e.target.value)} className="mt-1.5 w-full rounded-lg border border-slate-200 px-3.5 py-2.5 font-normal" /></label><label className="block text-sm font-medium text-slate-700">Location<input required value={location} onChange={(e) => setLocation(e.target.value)} className="mt-1.5 w-full rounded-lg border border-slate-200 px-3.5 py-2.5 font-normal" /></label></div><h2 className="pt-3 font-bold text-slate-900">Social links</h2><div className="grid gap-3 sm:grid-cols-2">{platforms.map((platform) => <label key={platform} className="block text-sm font-medium capitalize text-slate-700">{platform}<input type="url" placeholder="https://" value={links[platform] ?? ''} onChange={(e) => setLinks((current) => ({ ...current, [platform]: e.target.value }))} className="mt-1.5 w-full rounded-lg border border-slate-200 px-3.5 py-2.5 font-normal" /></label>)}</div>{error && <p className="text-sm text-rose-600">{error}</p>}{message && <p className="text-sm text-emerald-700">{message}</p>}<button className="rounded-lg bg-emerald-600 px-5 py-3 text-sm font-semibold text-white">Save shop profile</button></form>{shop && <p className="mt-5 text-xs text-slate-500">Public URL: /shop/{shop.slug}</p>}</div></div>;
}
