import { BadRequestException, ConflictException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { AuthUser } from '../auth/auth.service';
import { DatabaseService } from '../database/database.service';
import { PackagesService } from '../packages/packages.service';

interface ProductInput { name: string; description?: string; price: number; currency?: string; categoryId?: string; subcategoryId?: string; location: string; condition?: string; availability?: string; imageUrls?: string[] }

type ProductStatus = 'DRAFT' | 'PUBLISHED';

@Injectable()
export class ProductsService {
  constructor(private readonly db: DatabaseService, private readonly packages: PackagesService) {}

  async mine(user: AuthUser) { const vendor = await this.vendorFor(user); const rows = await this.db.connection('products').where({ vendor_profile_id: vendor.id }).orderBy('created_at', 'desc'); return Promise.all(rows.map((row) => this.toDto(row))); }

  async create(user: AuthUser, input: ProductInput) { const vendor = await this.vendorFor(user); this.validateInput(input); await this.assertCategory(input.categoryId, input.subcategoryId); const slug = await this.uniqueSlug(vendor.id, input.name); const row = await this.db.tx(async (trx) => { const [created] = await trx('products').insert({ vendor_profile_id: vendor.id, category_id: input.categoryId || null, subcategory_id: input.subcategoryId || null, name: input.name.trim(), slug, description: input.description?.trim() || null, price: input.price, currency: input.currency?.trim().toUpperCase() || 'RWF', location: input.location.trim(), condition: input.condition?.trim() || 'new', availability: input.availability?.trim() || 'in_stock' }).returning('*'); await this.insertImages(trx, created.id, input.imageUrls); await trx('audit_logs').insert({ actor_id: user.id, action: 'PRODUCT_CREATED', entity: 'product', entity_id: created.id, metadata: { name: created.name } }); return created; }); return this.toDto(row); }

  async update(user: AuthUser, id: string, input: Partial<ProductInput>) { const vendor = await this.vendorFor(user); const product = await this.owned(vendor.id, id); if (input.name !== undefined && input.name.trim().length < 2) throw new BadRequestException('Product name is too short'); if (input.price !== undefined && (!Number.isInteger(input.price) || input.price < 0)) throw new BadRequestException('Product price is invalid'); await this.assertCategory(input.categoryId, input.subcategoryId); const [row] = await this.db.connection('products').where({ id }).update({ ...(input.name !== undefined ? { name: input.name.trim() } : {}), ...(input.description !== undefined ? { description: input.description.trim() || null } : {}), ...(input.price !== undefined ? { price: input.price } : {}), ...(input.currency !== undefined ? { currency: input.currency.trim().toUpperCase() } : {}), ...(input.categoryId !== undefined ? { category_id: input.categoryId || null } : {}), ...(input.subcategoryId !== undefined ? { subcategory_id: input.subcategoryId || null } : {}), ...(input.location !== undefined ? { location: input.location.trim() } : {}), ...(input.condition !== undefined ? { condition: input.condition.trim() } : {}), ...(input.availability !== undefined ? { availability: input.availability.trim() } : {}), updated_at: this.db.connection.fn.now() }).returning('*'); if (input.imageUrls) { await this.db.connection('product_images').where({ product_id: id }).del(); await this.insertImages(this.db.connection, id, input.imageUrls); } await this.db.connection('audit_logs').insert({ actor_id: user.id, action: 'PRODUCT_UPDATED', entity: 'product', entity_id: id, metadata: {} }); return this.toDto(row ?? product); }

  async remove(user: AuthUser, id: string) { const vendor = await this.vendorFor(user); await this.owned(vendor.id, id); await this.db.connection('products').where({ id }).del(); await this.db.connection('audit_logs').insert({ actor_id: user.id, action: 'PRODUCT_DELETED', entity: 'product', entity_id: id, metadata: {} }); return { deleted: true }; }

  async publish(user: AuthUser, id: string, status: ProductStatus) { const vendor = await this.vendorFor(user); const product = await this.owned(vendor.id, id); if (status === 'PUBLISHED') { if (vendor.status !== 'ACTIVE') throw new ForbiddenException('Only active vendors can publish products'); const count = await this.db.connection('products').where({ vendor_profile_id: vendor.id, status: 'PUBLISHED' }).whereNot({ id }).count('id as count').first(); await this.packages.assertCanPublishProduct(vendor.id, Number(count?.count ?? 0)); } await this.db.connection('products').where({ id }).update({ status, updated_at: this.db.connection.fn.now() }); await this.db.connection('audit_logs').insert({ actor_id: user.id, action: status === 'PUBLISHED' ? 'PRODUCT_PUBLISHED' : 'PRODUCT_UNPUBLISHED', entity: 'product', entity_id: id, metadata: {} }); return this.toDto(await this.db.connection('products').where({ id }).first()); }

  async publicForVendor(vendorProfileId: string) { const rows = await this.db.connection('products as p').leftJoin('categories as c', 'c.id', 'p.category_id').leftJoin('subcategories as sc', 'sc.id', 'p.subcategory_id').where({ 'p.vendor_profile_id': vendorProfileId, 'p.status': 'PUBLISHED' }).select('p.*', 'c.name as category_name', 'sc.name as subcategory_name').orderBy('p.created_at', 'desc'); return Promise.all(rows.map((row) => this.toDto(row))); }

  private async vendorFor(user: AuthUser) { if (user.role !== 'VENDOR') throw new ForbiddenException('Only vendors can manage products'); const vendor = await this.db.connection('vendor_profiles').where({ user_id: user.id }).first(); if (!vendor) throw new NotFoundException('Vendor profile not found'); return vendor; }
  private async owned(vendorId: string, id: string) { const row = await this.db.connection('products').where({ id, vendor_profile_id: vendorId }).first(); if (!row) throw new NotFoundException('Product not found'); return row; }
  private validateInput(input: ProductInput) { if (!input.name?.trim() || input.name.trim().length < 2 || !input.location?.trim() || !Number.isInteger(input.price) || input.price < 0) throw new BadRequestException('Product fields are invalid'); }
  private async assertCategory(categoryId?: string, subcategoryId?: string) { if (subcategoryId && !categoryId) throw new BadRequestException('Subcategory requires a category'); if (categoryId && !(await this.db.connection('categories').where({ id: categoryId, is_active: true }).first())) throw new BadRequestException('Category is invalid'); if (subcategoryId && !(await this.db.connection('subcategories').where({ id: subcategoryId, category_id: categoryId, is_active: true }).first())) throw new BadRequestException('Subcategory is invalid'); }
  private async uniqueSlug(vendorId: string, name: string) { const base = name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 70) || 'product'; return `${base}-${Math.random().toString(36).slice(2, 8)}`; }
  private async insertImages(trx: any, productId: string, urls?: string[]) { if (!urls?.length) return; await trx('product_images').insert(urls.map((url, index) => ({ product_id: productId, url, sort_order: index, is_cover: index === 0 }))); }
  private async toDto(row: any) { const images = await this.db.connection('product_images').where({ product_id: row.id }).orderBy('sort_order', 'asc'); return { id: row.id, name: row.name, slug: row.slug, description: row.description, price: row.price, currency: row.currency, categoryId: row.category_id, categoryName: row.category_name, subcategoryId: row.subcategory_id, subcategoryName: row.subcategory_name, location: row.location, condition: row.condition, availability: row.availability, status: row.status as ProductStatus, images: images.map((image) => ({ id: image.id, url: image.url, sortOrder: image.sort_order, isCover: image.is_cover })), createdAt: row.created_at, updatedAt: row.updated_at }; }
}
