import { BadRequestException, ConflictException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { AuthUser } from '../auth/auth.service';
import { DatabaseService } from '../database/database.service';
import { PackagesService } from '../packages/packages.service';

interface ProductInput { name: string; description?: string; price: number; currency?: string; sku?: string; categoryId?: string; subcategoryId?: string; location: string; condition?: string; availability?: string; imageUrls?: string[] }

type ProductStatus = 'DRAFT' | 'PUBLISHED';

@Injectable()
export class ProductsService {
  constructor(private readonly db: DatabaseService, private readonly packages: PackagesService) {}

  async mine(user: AuthUser) { const vendor = await this.vendorFor(user); const rows = await this.db.connection('products').where({ vendor_profile_id: vendor.id }).orderBy('created_at', 'desc'); return Promise.all(rows.map((row) => this.toDto(row))); }

  async create(user: AuthUser, input: ProductInput) { const vendor = await this.vendorFor(user); this.validateInput(input); await this.assertCategory(input.categoryId, input.subcategoryId); const slug = await this.uniqueSlug(vendor.id, input.name); const row = await this.db.tx(async (trx) => { const [created] = await trx('products').insert({ vendor_profile_id: vendor.id, category_id: input.categoryId || null, subcategory_id: input.subcategoryId || null, name: input.name.trim(), slug, sku: input.sku?.trim() || null, description: input.description?.trim() || null, price: input.price, currency: input.currency?.trim().toUpperCase() || 'RWF', location: input.location.trim(), condition: input.condition?.trim() || 'new', availability: input.availability?.trim() || 'in_stock' }).returning('*'); await this.insertImages(trx, created.id, input.imageUrls); await trx('audit_logs').insert({ actor_id: user.id, action: 'PRODUCT_CREATED', entity: 'product', entity_id: created.id, metadata: { name: created.name } }); return created; }); return this.toDto(row); }

  async update(user: AuthUser, id: string, input: Partial<ProductInput>) { const vendor = await this.vendorFor(user); const product = await this.owned(vendor.id, id); if (input.name !== undefined && input.name.trim().length < 2) throw new BadRequestException('Product name is too short'); if (input.price !== undefined && (!Number.isInteger(input.price) || input.price < 0)) throw new BadRequestException('Product price is invalid'); await this.assertCategory(input.categoryId, input.subcategoryId); const [row] = await this.db.connection('products').where({ id }).update({ ...(input.name !== undefined ? { name: input.name.trim() } : {}), ...(input.description !== undefined ? { description: input.description.trim() || null } : {}), ...(input.price !== undefined ? { price: input.price } : {}), ...(input.currency !== undefined ? { currency: input.currency.trim().toUpperCase() } : {}), ...(input.sku !== undefined ? { sku: input.sku.trim() || null } : {}), ...(input.categoryId !== undefined ? { category_id: input.categoryId || null } : {}), ...(input.subcategoryId !== undefined ? { subcategory_id: input.subcategoryId || null } : {}), ...(input.location !== undefined ? { location: input.location.trim() } : {}), ...(input.condition !== undefined ? { condition: input.condition.trim() } : {}), ...(input.availability !== undefined ? { availability: input.availability.trim() } : {}), updated_at: this.db.connection.fn.now() }).returning('*'); if (input.imageUrls) { await this.db.connection('product_images').where({ product_id: id }).del(); await this.insertImages(this.db.connection, id, input.imageUrls); } await this.db.connection('audit_logs').insert({ actor_id: user.id, action: 'PRODUCT_UPDATED', entity: 'product', entity_id: id, metadata: { sku: input.sku ?? product.sku } }); return this.toDto(row ?? product); }

  async remove(user: AuthUser, id: string) { const vendor = await this.vendorFor(user); await this.owned(vendor.id, id); await this.db.connection('products').where({ id }).del(); await this.db.connection('audit_logs').insert({ actor_id: user.id, action: 'PRODUCT_DELETED', entity: 'product', entity_id: id, metadata: {} }); return { deleted: true }; }

  async publish(user: AuthUser, id: string, status: ProductStatus) { const vendor = await this.vendorFor(user); const product = await this.owned(vendor.id, id); if (status === 'PUBLISHED') { if (vendor.status !== 'ACTIVE') throw new ForbiddenException('Only active vendors can publish products'); const count = await this.db.connection('products').where({ vendor_profile_id: vendor.id, status: 'PUBLISHED' }).whereNot({ id }).count('id as count').first(); await this.packages.assertCanPublishProduct(vendor.id, Number(count?.count ?? 0)); } await this.db.connection('products').where({ id }).update({ status, updated_at: this.db.connection.fn.now() }); await this.db.connection('audit_logs').insert({ actor_id: user.id, action: status === 'PUBLISHED' ? 'PRODUCT_PUBLISHED' : 'PRODUCT_UNPUBLISHED', entity: 'product', entity_id: id, metadata: {} }); return this.toDto(await this.db.connection('products').where({ id }).first()); }

  async addImages(user: AuthUser, id: string, urls: string[]) { const vendor = await this.vendorFor(user); await this.owned(vendor.id, id); if (!urls.length) throw new BadRequestException('At least one image URL is required'); await this.insertImages(this.db.connection, id, urls); return this.toDto(await this.db.connection('products').where({ id }).first()); }
  async deleteImage(user: AuthUser, productId: string, imageId: string) { const vendor = await this.vendorFor(user); await this.owned(vendor.id, productId); const deleted = await this.db.connection('product_images').where({ id: imageId, product_id: productId }).del(); if (!deleted) throw new NotFoundException('Product image not found'); return this.toDto(await this.db.connection('products').where({ id: productId }).first()); }
  async reorderImages(user: AuthUser, productId: string, imageIds: string[]) { const vendor = await this.vendorFor(user); await this.owned(vendor.id, productId); const images = await this.db.connection('product_images').where({ product_id: productId }).select('id'); if (images.length !== imageIds.length || new Set(images.map((image) => image.id)).size !== new Set(imageIds).size || !imageIds.every((id) => images.some((image) => image.id === id))) throw new BadRequestException('Image order must include every product image exactly once'); await this.db.tx(async (trx) => { for (const [sortOrder, id] of imageIds.entries()) await trx('product_images').where({ id, product_id: productId }).update({ sort_order: sortOrder }); }); return this.toDto(await this.db.connection('products').where({ id: productId }).first()); }
  async setCoverImage(user: AuthUser, productId: string, imageId: string) { const vendor = await this.vendorFor(user); await this.owned(vendor.id, productId); const image = await this.db.connection('product_images').where({ id: imageId, product_id: productId }).first(); if (!image) throw new NotFoundException('Product image not found'); await this.db.tx(async (trx) => { await trx('product_images').where({ product_id: productId }).update({ is_cover: false }); await trx('product_images').where({ id: imageId }).update({ is_cover: true }); }); return this.toDto(await this.db.connection('products').where({ id: productId }).first()); }

  async variants(user: AuthUser, productId: string) { const vendor = await this.vendorFor(user); await this.owned(vendor.id, productId); return this.variantDtos(await this.db.connection('product_variants').where({ product_id: productId }).orderBy('created_at', 'asc')); }
  async createVariant(user: AuthUser, productId: string, input: any) { const vendor = await this.vendorFor(user); await this.owned(vendor.id, productId); if (!input.sku?.trim()) throw new BadRequestException('Variant SKU is required'); if (!Number.isInteger(input.stock) || input.stock < 0) throw new BadRequestException('Variant stock is invalid'); try { const [row] = await this.db.connection('product_variants').insert({ product_id: productId, sku: input.sku.trim(), color: input.color?.trim() || null, size: input.size?.trim() || null, storage: input.storage?.trim() || null, model: input.model?.trim() || null, price: input.price ?? null, stock: input.stock, availability: input.availability?.trim() || 'in_stock' }).returning('*'); return this.variantDtos([row]).then((items) => items[0]); } catch (error) { if ((error as { code?: string }).code === '23505') throw new ConflictException('Variant SKU already exists for this product'); throw error; } }
  async updateVariant(user: AuthUser, productId: string, variantId: string, input: any) { const vendor = await this.vendorFor(user); await this.owned(vendor.id, productId); const variant = await this.db.connection('product_variants').where({ id: variantId, product_id: productId }).first(); if (!variant) throw new NotFoundException('Variant not found'); const [row] = await this.db.connection('product_variants').where({ id: variantId }).update({ ...(input.sku !== undefined ? { sku: input.sku.trim() } : {}), ...(input.color !== undefined ? { color: input.color.trim() || null } : {}), ...(input.size !== undefined ? { size: input.size.trim() || null } : {}), ...(input.storage !== undefined ? { storage: input.storage.trim() || null } : {}), ...(input.model !== undefined ? { model: input.model.trim() || null } : {}), ...(input.price !== undefined ? { price: input.price } : {}), ...(input.stock !== undefined ? { stock: input.stock } : {}), ...(input.availability !== undefined ? { availability: input.availability.trim() } : {}), ...(input.isActive !== undefined ? { is_active: input.isActive } : {}), updated_at: this.db.connection.fn.now() }).returning('*'); return (await this.variantDtos([row]))[0]; }
  async deleteVariant(user: AuthUser, productId: string, variantId: string) { const vendor = await this.vendorFor(user); await this.owned(vendor.id, productId); const deleted = await this.db.connection('product_variants').where({ id: variantId, product_id: productId }).del(); if (!deleted) throw new NotFoundException('Variant not found'); return { deleted: true }; }

  async publicForVendor(vendorProfileId: string) { const rows = await this.db.connection('products as p').leftJoin('categories as c', 'c.id', 'p.category_id').leftJoin('subcategories as sc', 'sc.id', 'p.subcategory_id').where({ 'p.vendor_profile_id': vendorProfileId, 'p.status': 'PUBLISHED' }).select('p.*', 'c.name as category_name', 'sc.name as subcategory_name').orderBy('p.created_at', 'desc'); return Promise.all(rows.map((row) => this.toDto(row))); }
  async publicList(filters: { search?: string; categoryId?: string; vendorId?: string; location?: string; condition?: string; minPrice?: number; maxPrice?: number; sort?: string; page?: number; limit?: number }) { const page = Math.max(1, filters.page || 1); const limit = Math.min(50, Math.max(1, filters.limit || 20)); const query = this.db.connection('products as p').join('vendor_profiles as v', 'v.id', 'p.vendor_profile_id').leftJoin('categories as c', 'c.id', 'p.category_id').leftJoin('subcategories as sc', 'sc.id', 'p.subcategory_id').where({ 'p.status': 'PUBLISHED', 'v.status': 'ACTIVE' }).select('p.*', 'c.name as category_name', 'sc.name as subcategory_name', 'v.business_name as vendor_name', 'v.slug as vendor_slug'); if (filters.search) query.where((builder) => builder.whereILike('p.name', `%${filters.search}%`).orWhereILike('p.description', `%${filters.search}%`).orWhereILike('v.business_name', `%${filters.search}%`)); if (filters.categoryId) query.where('p.category_id', filters.categoryId); if (filters.vendorId) query.where('p.vendor_profile_id', filters.vendorId); if (filters.location) query.whereILike('p.location', `%${filters.location}%`); if (filters.condition) query.where('p.condition', filters.condition); if (filters.minPrice !== undefined) query.where('p.price', '>=', filters.minPrice); if (filters.maxPrice !== undefined) query.where('p.price', '<=', filters.maxPrice); const countQuery = query.clone().clearSelect().clearOrder().countDistinct('p.id as count').first(); if (filters.sort === 'price_asc') query.orderBy('p.price', 'asc'); else if (filters.sort === 'price_desc') query.orderBy('p.price', 'desc'); else query.orderBy('p.created_at', 'desc'); const [rows, count] = await Promise.all([query.offset((page - 1) * limit).limit(limit), countQuery]); return { items: await Promise.all(rows.map((row) => this.toDto({ ...row, vendorName: row.vendor_name, vendorSlug: row.vendor_slug }))), page, limit, total: Number(count?.count || 0) }; }
  async publicBySlug(slug: string) { const row = await this.db.connection('products as p').join('vendor_profiles as v', 'v.id', 'p.vendor_profile_id').leftJoin('categories as c', 'c.id', 'p.category_id').leftJoin('subcategories as sc', 'sc.id', 'p.subcategory_id').where((builder) => builder.where({ 'p.slug': slug }).orWhere({ 'p.id': slug })).where({ 'p.status': 'PUBLISHED', 'v.status': 'ACTIVE' }).select('p.*', 'c.name as category_name', 'sc.name as subcategory_name', 'v.business_name as vendor_name', 'v.slug as vendor_slug', 'v.phone as vendor_phone', 'v.location as vendor_location').first(); if (!row) throw new NotFoundException('Published product not found'); return { ...(await this.toDto(row)), vendor: { name: row.vendor_name, slug: row.vendor_slug, phone: row.vendor_phone, location: row.vendor_location } }; }

  async publicReviews(identifier: string) { const product = await this.db.connection('products').where((query) => query.where({ id: identifier }).orWhere({ slug: identifier })).select('id').first(); if (!product) return []; return this.db.connection('product_reviews').where({ product_id: product.id }).orderBy('created_at', 'desc'); }
  private async vendorFor(user: AuthUser) { if (user.role !== 'VENDOR') throw new ForbiddenException('Only vendors can manage products'); const vendor = await this.db.connection('vendor_profiles').where({ user_id: user.id }).first(); if (!vendor) throw new NotFoundException('Vendor profile not found'); return vendor; }
  private async owned(vendorId: string, id: string) { const row = await this.db.connection('products').where({ id, vendor_profile_id: vendorId }).first(); if (!row) throw new NotFoundException('Product not found'); return row; }
  private validateInput(input: ProductInput) { if (!input.name?.trim() || input.name.trim().length < 2 || !input.location?.trim() || !Number.isInteger(input.price) || input.price < 0) throw new BadRequestException('Product fields are invalid'); }
  private async assertCategory(categoryId?: string, subcategoryId?: string) { if (subcategoryId && !categoryId) throw new BadRequestException('Subcategory requires a category'); if (categoryId && !(await this.db.connection('categories').where({ id: categoryId, is_active: true }).first())) throw new BadRequestException('Category is invalid'); if (subcategoryId && !(await this.db.connection('subcategories').where({ id: subcategoryId, category_id: categoryId, is_active: true }).first())) throw new BadRequestException('Subcategory is invalid'); }
  private async uniqueSlug(vendorId: string, name: string) { const base = name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 70) || 'product'; return `${base}-${Math.random().toString(36).slice(2, 8)}`; }
  private async insertImages(trx: any, productId: string, urls?: string[]) { if (!urls?.length) return; await trx('product_images').insert(urls.map((url, index) => ({ product_id: productId, url, sort_order: index, is_cover: index === 0 }))); }
  private async toDto(row: any) { const images = await this.db.connection('product_images').where({ product_id: row.id }).orderBy('sort_order', 'asc'); const variants = await this.db.connection('product_variants').where({ product_id: row.id }).orderBy('created_at', 'asc'); return { id: row.id, name: row.name, slug: row.slug, sku: row.sku, description: row.description, price: row.price, currency: row.currency, categoryId: row.category_id, categoryName: row.category_name, subcategoryId: row.subcategory_id, subcategoryName: row.subcategory_name, location: row.location, condition: row.condition, availability: row.availability, status: row.status as ProductStatus, vendorName: row.vendor_name, vendorSlug: row.vendor_slug, images: images.map((image) => ({ id: image.id, url: image.url, sortOrder: image.sort_order, isCover: image.is_cover })), variants: this.variantDtosSync(variants), createdAt: row.created_at, updatedAt: row.updated_at }; }
  private async variantDtos(rows: any[]) { return this.variantDtosSync(rows); }
  private variantDtosSync(rows: any[]) { return rows.map((row) => ({ id: row.id, sku: row.sku, color: row.color, size: row.size, storage: row.storage, model: row.model, price: row.price, stock: row.stock, availability: row.availability, isActive: row.is_active })); }
}
