import { BadRequestException, ConflictException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { AuthUser } from '../auth/auth.service';
import { DatabaseService } from '../database/database.service';

interface ItemInput { name: string; sku?: string; openingQuantity?: number; lowStockThreshold?: number; productId?: string; variantId?: string; notes?: string }
type MovementType = 'ADDITION' | 'SALE' | 'ADJUSTMENT';

@Injectable()
export class InventoryService {
  constructor(private readonly db: DatabaseService) {}

  async list(user: AuthUser) { const vendor = await this.vendorFor(user); const rows = await this.db.connection('inventory_items').where({ vendor_profile_id: vendor.id, status: 'ACTIVE' }).orderBy('created_at', 'desc'); return Promise.all(rows.map((row) => this.toDto(row))); }

  async create(user: AuthUser, input: ItemInput) { const vendor = await this.vendorFor(user); this.validate(input); if (input.productId && !(await this.db.connection('products').where({ id: input.productId, vendor_profile_id: vendor.id }).first())) throw new BadRequestException('Product is not owned by this vendor'); if (input.variantId && !(await this.db.connection('product_variants as v').join('products as p', 'p.id', 'v.product_id').where({ 'v.id': input.variantId, 'p.vendor_profile_id': vendor.id }).first())) throw new BadRequestException('Variant is not owned by this vendor'); try { const row = await this.db.tx(async (trx) => { const [created] = await trx('inventory_items').insert({ vendor_profile_id: vendor.id, product_id: input.productId || null, variant_id: input.variantId || null, name: input.name.trim(), sku: input.sku?.trim() || null, opening_quantity: input.openingQuantity ?? 0, low_stock_threshold: input.lowStockThreshold ?? 5, notes: input.notes?.trim() || null }).returning('*'); if ((input.openingQuantity ?? 0) > 0) await trx('stock_movements').insert({ inventory_item_id: created.id, type: 'OPENING', quantity_delta: input.openingQuantity, created_by: user.id, note: 'Opening stock' }); return created; }); return this.toDto(row); } catch (error) { if ((error as { code?: string }).code === '23505') throw new ConflictException('Inventory item already exists'); throw error; } }

  async update(user: AuthUser, id: string, input: Partial<ItemInput>) { const vendor = await this.vendorFor(user); await this.owned(vendor.id, id); if (input.name !== undefined && input.name.trim().length < 2) throw new BadRequestException('Inventory name is too short'); if (input.lowStockThreshold !== undefined && (!Number.isInteger(input.lowStockThreshold) || input.lowStockThreshold < 0)) throw new BadRequestException('Low-stock threshold is invalid'); const [row] = await this.db.connection('inventory_items').where({ id }).update({ ...(input.name !== undefined ? { name: input.name.trim() } : {}), ...(input.sku !== undefined ? { sku: input.sku.trim() || null } : {}), ...(input.lowStockThreshold !== undefined ? { low_stock_threshold: input.lowStockThreshold } : {}), ...(input.notes !== undefined ? { notes: input.notes.trim() || null } : {}), updated_at: this.db.connection.fn.now() }).returning('*'); return this.toDto(row); }

  async archive(user: AuthUser, id: string) { const vendor = await this.vendorFor(user); await this.owned(vendor.id, id); await this.db.connection('inventory_items').where({ id }).update({ status: 'ARCHIVED', updated_at: this.db.connection.fn.now() }); return { archived: true }; }

  async addStock(user: AuthUser, id: string, quantity: number, note?: string) { return this.move(user, id, 'ADDITION', quantity, note); }
  async recordSale(user: AuthUser, id: string, quantity: number, note?: string) { return this.move(user, id, 'SALE', -quantity, note); }
  async adjust(user: AuthUser, id: string, quantityDelta: number, note?: string) { return this.move(user, id, 'ADJUSTMENT', quantityDelta, note); }

  async movements(user: AuthUser, id: string) { const vendor = await this.vendorFor(user); await this.owned(vendor.id, id); return this.db.connection('stock_movements').where({ inventory_item_id: id }).orderBy('created_at', 'desc'); }

  async summary(user: AuthUser) { const items = await this.list(user); return { totalItems: items.length, totalRemaining: items.reduce((sum, item) => sum + item.remainingQuantity, 0), totalSold: items.reduce((sum, item) => sum + item.soldQuantity, 0), lowStockItems: items.filter((item) => item.stockStatus !== 'IN_STOCK').length, items }; }

  private async move(user: AuthUser, id: string, type: MovementType, delta: number, note?: string) { const vendor = await this.vendorFor(user); if (!Number.isInteger(delta) || delta === 0) throw new BadRequestException('Stock movement quantity cannot be zero'); if (type === 'SALE' && delta > 0) delta = -delta; const result = await this.db.tx(async (trx) => { const item = await trx('inventory_items').where({ id, vendor_profile_id: vendor.id, status: 'ACTIVE' }).forUpdate().first(); if (!item) throw new NotFoundException('Inventory item not found'); const movementTotal = await trx('stock_movements').where({ inventory_item_id: id }).whereNot({ type: 'OPENING' }).sum('quantity_delta as total').first(); const remaining = Number(item.opening_quantity) + Number(movementTotal?.total ?? 0); if (remaining + delta < 0) throw new BadRequestException(`Insufficient stock (remaining ${remaining})`); await trx('stock_movements').insert({ inventory_item_id: id, type, quantity_delta: delta, note: note?.trim() || null, created_by: user.id }); await trx('inventory_items').where({ id }).update({ updated_at: trx.fn.now() }); return trx('inventory_items').where({ id }).first(); }); return this.toDto(result); }

  private async vendorFor(user: AuthUser) { if (user.role !== 'VENDOR') throw new ForbiddenException('Only vendors can manage inventory'); const vendor = await this.db.connection('vendor_profiles').where({ user_id: user.id }).first(); if (!vendor) throw new NotFoundException('Vendor profile not found'); return vendor; }
  private async owned(vendorId: string, id: string) { const row = await this.db.connection('inventory_items').where({ id, vendor_profile_id: vendorId, status: 'ACTIVE' }).first(); if (!row) throw new NotFoundException('Inventory item not found'); return row; }
  private validate(input: ItemInput) { if (!input.name?.trim() || input.name.trim().length < 2 || !Number.isInteger(input.openingQuantity ?? 0) || (input.openingQuantity ?? 0) < 0 || !Number.isInteger(input.lowStockThreshold ?? 5) || (input.lowStockThreshold ?? 5) < 0) throw new BadRequestException('Inventory fields are invalid'); }
  private async toDto(row: any) { const totals = await this.db.connection('stock_movements').where({ inventory_item_id: row.id }).select(this.db.connection.raw("coalesce(sum(case when type <> 'OPENING' then quantity_delta else 0 end), 0) as total"), this.db.connection.raw("coalesce(sum(case when type = 'ADDITION' then quantity_delta else 0 end), 0) as added"), this.db.connection.raw("coalesce(sum(case when type = 'SALE' then -quantity_delta else 0 end), 0) as sold" )).first(); const remaining = Number(row.opening_quantity) + Number(totals?.total ?? 0); const sold = Number(totals?.sold ?? 0); return { id: row.id, name: row.name, sku: row.sku, productId: row.product_id, variantId: row.variant_id, openingQuantity: row.opening_quantity, addedQuantity: Number(totals?.added ?? 0), soldQuantity: sold, remainingQuantity: remaining, lowStockThreshold: row.low_stock_threshold, stockStatus: remaining <= 0 ? 'OUT_OF_STOCK' : remaining <= row.low_stock_threshold ? 'LOW_STOCK' : 'IN_STOCK', notes: row.notes, status: row.status, createdAt: row.created_at, updatedAt: row.updated_at }; }
}
