import { demoCategories } from './demoData';
import { getSellerAnalytics, getSellerOrders } from './seller';
import { productsApi, type Product } from './products';

export type ReviewStatus = 'PENDING_REVIEW' | 'APPROVED' | 'REJECTED';
export interface ModerationListing extends Product { reviewStatus: ReviewStatus; submittedAt: string; sellerName: string; moderationNote?: string }
export interface PlatformAnalytics { totalListings: number; pendingListings: number; approvedListings: number; rejectedListings: number; totalCategories: number; totalSubcategories: number; totalOrders: number; platformRevenue: number; activeSellers: number; customerAccounts: number; approvalRate: number }
const MODERATION_KEY = 'market.demo.moderation.v1';
function readDecisions(): Record<string, { reviewStatus: ReviewStatus; moderationNote?: string }> { try { return JSON.parse(window.localStorage.getItem(MODERATION_KEY) ?? '{}') as Record<string, { reviewStatus: ReviewStatus; moderationNote?: string }>; } catch { return {}; } }
function saveDecisions(value: Record<string, { reviewStatus: ReviewStatus; moderationNote?: string }>) { try { window.localStorage.setItem(MODERATION_KEY, JSON.stringify(value)); } catch { /* unavailable */ } }
function defaultStatus(index: number): ReviewStatus { return index === 1 ? 'PENDING_REVIEW' : index === 3 ? 'REJECTED' : 'APPROVED'; }
export async function getModerationListings(): Promise<ModerationListing[]> { const decisions = readDecisions(); const products = await productsApi.mine(); return products.map((product, index) => ({ ...product, reviewStatus: decisions[product.id]?.reviewStatus ?? defaultStatus(index), moderationNote: decisions[product.id]?.moderationNote, submittedAt: new Date(Date.now() - (index + 1) * 86400000).toISOString(), sellerName: 'Demo seller' })); }
export async function moderateListing(id: string, reviewStatus: Exclude<ReviewStatus, 'PENDING_REVIEW'>, moderationNote?: string) { const decisions = readDecisions(); decisions[id] = { reviewStatus, moderationNote }; saveDecisions(decisions); return getModerationListings(); }
export async function getPlatformAnalytics(): Promise<PlatformAnalytics> { const listings = await getModerationListings(); const sellerAnalytics = await getSellerAnalytics(); const orders = await getSellerOrders(); const approvedListings = listings.filter((item) => item.reviewStatus === 'APPROVED').length; return { totalListings: listings.length, pendingListings: listings.filter((item) => item.reviewStatus === 'PENDING_REVIEW').length, approvedListings, rejectedListings: listings.filter((item) => item.reviewStatus === 'REJECTED').length, totalCategories: demoCategories.length, totalSubcategories: demoCategories.length * 3, totalOrders: orders.length, platformRevenue: sellerAnalytics.revenue, activeSellers: Math.max(1, new Set(listings.map((item) => item.sellerName)).size), customerAccounts: 128, approvalRate: listings.length ? Math.round((approvedListings / listings.length) * 100) : 0 }; }
