import type { Category, Product } from '../types';
import { getMarketplaceProduct, searchMarketplace } from './marketplace';

export type SortKey = 'featured' | 'newest' | 'price-asc' | 'price-desc' | 'rating';
export interface ProductQuery { category?: string; tag?: string; q?: string; minPrice?: number; maxPrice?: number; minRating?: number; inStockOnly?: boolean; sort?: SortKey; }
interface MarketplaceProduct { id: string; name: string; slug?: string; description?: string; price: number; categoryId?: string; categoryName?: string; location?: string; availability?: string; rating?: number; reviewCount?: number; images?: { url: string; isCover?: boolean }[]; variants?: { stock?: number; isActive?: boolean }[]; createdAt?: string; }
interface MarketplaceCategory { id: string; name: string; slug: string; description?: string | null; subcategories?: { id: string; name: string; slug: string }[]; }
const toProduct = (item: MarketplaceProduct): Product => { const image = item.images?.find((entry) => entry.isCover)?.url ?? item.images?.[0]?.url ?? 'https://placehold.co/800x800/e2e8f0/475569?text=Market'; const stock = (item.variants ?? []).filter((variant) => variant.isActive !== false).reduce((sum, variant) => sum + Number(variant.stock ?? 0), 0); return { id: item.id, slug: item.slug, name: item.name, categorySlug: (item.categoryName ?? 'products').toLowerCase().replace(/[^a-z0-9]+/g, '-'), categoryName: item.categoryName ?? 'Products', price: item.price, description: item.description ?? '', specs: item.location ? [{ label: 'Location', value: item.location }] : [], image, stock: stock || (item.availability === 'out_of_stock' ? 0 : 1), tags: [], rating: Number(item.rating ?? 0), reviewCount: Number(item.reviewCount ?? 0), createdAt: item.createdAt ?? new Date().toISOString() }; };
const toCategory = (row: MarketplaceCategory): Category => ({ slug: row.slug, name: row.name, shortName: row.name, description: row.description ?? '', image: 'https://placehold.co/600x400/e2e8f0/475569?text=' + encodeURIComponent(row.name) });
export const api = { async getCategories(): Promise<Category[]> { const response = await fetch('/api/categories', { credentials: 'include' }); if (!response.ok) throw new Error('Unable to load categories'); const rows = await response.json() as MarketplaceCategory[]; return rows.map(toCategory); }, async getProducts(query: ProductQuery = {}): Promise<Product[]> { const result = await searchMarketplace({ search: query.q, minPrice: query.minPrice, maxPrice: query.maxPrice, sort: query.sort === 'price-asc' ? 'price_asc' : query.sort === 'price-desc' ? 'price_desc' : query.sort === 'newest' ? 'newest' : undefined, limit: 50 }); let items = result.items.map((item) => toProduct(item as MarketplaceProduct)); const category = query.category; if (query.inStockOnly) items = items.filter((item) => item.stock > 0); if (category) items = items.filter((item) => item.categorySlug === category || item.categoryName.toLowerCase() === category.toLowerCase()); if (query.minRating) items = items.filter((item) => item.rating >= query.minRating!); return items; }, async getProduct(id: string): Promise<Product> { return toProduct(await getMarketplaceProduct(id) as MarketplaceProduct); }, async getRelated(product: Product, count = 8): Promise<Product[]> { const items = await this.getProducts({ category: product.categorySlug }); return items.filter((item) => item.id !== product.id).slice(0, count); } };
